---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "${TRANSFORMER_NAME}-pvc"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "${TRANSFORMER_NAME}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "${TRANSFORMER_NAME}"
  template:
    metadata:
      labels:
        app: "${TRANSFORMER_NAME}"
    spec:
      serviceAccountName: "${TRANSFORMER_SERVICE_ACCOUNT_NAME}"
      containers:
        - name: "${TRANSFORMER_NAME}"
          image: "${TRANSFORMER_IMAGE}"
          ports:
            - containerPort: ${TRANSFORMER_PORT}
              protocol: TCP
          env:
            - name: dpm_conf_dpm_enabled
              value: "true"
            - name: dpm_conf_dpm_base_url
              valueFrom:
                configMapKeyRef:
                  name: "${TRANSFORMER_NAME}-config"
                  key: sch_url
            - name: dpm_conf_dpm_remote_control_job_labels
              value: "${TRANSFORMER_LABELS}"
            - name: transformer_token_string
              valueFrom:
                secretKeyRef:
                  name: "${TRANSFORMER_NAME}-creds"
                  key: transformer_token_string
            - name: transformer_id
              valueFrom:
                configMapKeyRef:
                  name: "${TRANSFORMER_NAME}-config"
                  key: transformer_id
            - name: transformer_conf_transformer_base_http_url
              valueFrom:
                configMapKeyRef:
                  name: "${TRANSFORMER_NAME}-config"
                  key: transformer_external_url
            - name: transformer_conf_kubernetes_ingress_service_enabled
              value: "true"
            - name: transformer_conf_kubernetes_namespace
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: transformer_conf_kubernetes_serviceAccountName
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
            - name: transformer_conf_kubernetes_persistent_volume_name
              value: "${TRANSFORMER_NAME}-vol"
            - name: transformer_conf_kubernetes_persistent_volume_mountPath
              value: "/streamsets"
            - name: transformer_conf_kubernetes_persistent_volume_claimName
              value: "${TRANSFORMER_NAME}-pvc"
          volumeMounts:
      volumes:
        - name: "${TRANSFORMER_NAME}-vol"
          persistentVolumeClaim:
            claimName: "${TRANSFORMER_NAME}-pvc"
